### ISSUE TITLE
React peer dependency

### ISSUE THREAD

**Issue by gburnett** [tacomanator/react-detect-print#5]
I can see a [peer dependency on React 17](https://github.com/tacomanator/react-detect-print/blob/09589f5f1b8283413936dc4e95ef493b1c4255be/package.json#L33).

I think that hooks are supported from `v16.8`.  Any reason to recommend 17 instead?

**Comment by razor247** [comment]
Can we up this to the latest React 18 now?

**Comment by tacomanator** [comment]
broadened peer dependency in b9b3f06366828b72e35b724fd461777edf346aa6
